version: 2
updates:
  # 1. Configuración para el Backend (Java / Maven)
  - package-ecosystem: "maven"
    directory: "/back" # Esta ruta apunta a la carpeta del backend
    schedule:
      interval: "weekly"
      day: "monday"
    commit-message:
      prefix: "chore(back)"
    ignore:
      - dependency-name: "org.springframework.boot:*"
        versions:
          - ">= 4.0.0"
    groups:
      spring-boot-updates:
        patterns:
          - "org.springframework.boot:*"
      all-other-maven:
        patterns:
          - "*"

  # 2. Configuración para el Frontend (Angular / pnpm)
  - package-ecosystem: "npm"
    directory: "/front"
    schedule:
      interval: "weekly"
      day: "monday"

    commit-message:
      prefix: "chore(front)"
    ignore:
      - dependency-name: "@angular/*"
        versions:
          - ">=22.0.0"
      - dependency-name: "@angular-devkit/*"
        versions:
          - ">=22.0.0"
    groups:
      angular-updates:
        patterns:
          - "@angular/*"
      all-other-frontend:
        patterns:
          - "*"

  # 3. Configuración para el Middleware (C# / .NET)
  - package-ecosystem: "nuget"
    directory: "/middleware"
    schedule:
      interval: "weekly"
      day: "monday"
    commit-message:
      prefix: "chore(middleware)"
    groups:
      dotnet-updates:
        patterns:
          - "*"

  # 4. Configuración para los propios Workflows de GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    commit-message:
      prefix: "chore(actions)"
    groups:
      actions-updates:
        patterns:
          - "*"