version: '3.8'
services:
  postgres-dev:
    image: postgres:15-alpine
    container_name: trazzo-db-dev
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: trazzo_dev
      POSTGRES_PASSWORD: trazzo_dev_pass
      POSTGRES_DB: trazzo_dev_db