server {
    listen 80;
    server_name trazzosaas.noahtechperu.com;
    root /usr/share/nginx/html;
    index index.html;

    # Compresión Gzip para mejorar el rendimiento de carga
    gzip on;
    gzip_types text/plain text/css application/json application/javascript;

    # Configuración de caché a largo plazo para archivos estáticos (js, css)
    location ~* \.(?:css|js)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    # Redirección SPA: Si el archivo o directorio no existe, redirigir a index.html
    location / {
        try_files $uri $uri/ /index.html;

        # Evitar el cacheo del index.html para que los usuarios siempre reciban la última versión de la app
        add_header Cache-Control "no-store, no-cache, must-revalidate";
    }
}
