server {
    listen 8080;
    server_name trazzosaas.noahtechperu.com;

    client_body_temp_path /tmp/nginx/client_temp;
    proxy_temp_path        /tmp/nginx/proxy_temp;
    fastcgi_temp_path      /tmp/nginx/fastcgi_temp;
    uwsgi_temp_path        /tmp/nginx/uwsgi_temp;
    scgi_temp_path         /tmp/nginx/scgi_temp;
    root /usr/share/nginx/html;
    index index.html;

    # Compresion Gzip para mejorar el rendimiento de carga
    gzip on;
    gzip_types text/plain text/css application/json application/javascript;

    # Configuracion de cache a largo plazo para archivos estaticos (js, css)
    location ~* \.(?:css|js)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    # Reenvia las llamadas del frontend al backend dentro de la red de Docker.
    location /api/ {
        # 1. Le decimos a Nginx que use el DNS interno de Docker para resolver nombres
        resolver 127.0.0.11 valid=30s;
        
        # 2. Guardamos la URL en una variable (esto evita el crash en el arranque/CI)
        set $upstream_back http://trazzo-backend:8080;
        
        # 3. Pasamos la variable
        proxy_pass $upstream_back;
        
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Redireccion SPA: Si el archivo o directorio no existe, redirigir a index.html
    location / {
        try_files $uri $uri/ /index.html;

        # Evitar el cacheo del index.html para que los usuarios siempre reciban la ultima version de la app
        add_header Cache-Control "no-store, no-cache, must-revalidate";
    }
}
