server {
    listen 8080;
    server_name trazzosaas.noahtechperu.com;
    root /usr/share/nginx/html;
    index index.html;

    # Compresion Gzip para mejorar el rendimiento de carga
    gzip on;
    gzip_types text/plain text/css application/json application/javascript;

    # Configuracion de cache a largo plazo para archivos estaticos (js, css)
    location ~* \.(?:css|js)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    # Reenvia las llamadas del frontend al backend dentro de la red de Docker.
    location /api/ {
        proxy_pass http://trazzo-backend:8080;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Redireccion SPA: Si el archivo o directorio no existe, redirigir a index.html
    location / {
        try_files $uri $uri/ /index.html;

        # Evitar el cacheo del index.html para que los usuarios siempre reciban la ultima version de la app
        add_header Cache-Control "no-store, no-cache, must-revalidate";
    }
}
