sonar.projectKey=trazzo-camera
sonar.projectName=Trazzo Camera Biometric Agent
sonar.projectVersion=1.0.0

sonar.sources=src
sonar.tests=tests

sonar.python.version=3.14
sonar.language=py
sonar.sourceEncoding=UTF-8

sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=junit.xml

# excluir codigo no aplicable a coverage/analisis funcional
sonar.exclusions=**/models/**,**/__pycache__/**,scripts/**,test_camera.py,.venv/**
sonar.coverage.exclusions=src/__init__.py,src/*/__init__.py,src/server.py,test_camera.py

# gates de calidad
sonar.qualitygate.wait=true
