name: Validar Mensajes de Commit (Commitlint)

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    name: Revisar historial de commits
    steps:
      - name: Checkout del código
        uses: actions/checkout@v7
        with:
          fetch-depth: 0 # Crítico: Necesita el historial del PR para validar todos los commits nuevos

      - name: Ejecutar Commitlint
        uses: wagoid/commitlint-github-action@v6
        with:
          configFile: commitlint.config.mjs
