name: Seguridad - Revisión de Dependencias

on:
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read
  pull-requests: write # Necesario para comentar en el PR si encuentra fallos

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    name: Analizar librerías introducidas
    steps:
      - name: Checkout del código
        uses: actions/checkout@v6

      - name: Ejecutar Dependency Review
        uses: actions/dependency-review-action@v5
        with:
          fail-on-severity: moderate # Bloqueará el PR si la vulnerabilidad es Moderada, Alta o Crítica
          deny-licenses: GPL-3.0, AGPL-3.0 # Opcional: Bloquea licencias víricas que te obliguen a hacer Trazzo open-source